name: 'Auto Assign Action'
description: 'Add reviewers to pull requests when pull requests are opened.'
author: 'Kentaro Matsushita'
inputs:
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  configuration-path:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'
outputs:
  reviewers_count:
    description: 'The number of assigned reviewers'
  reviewers:
    description: 'The list of assigned reviewers'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'user-plus'
  color: 'blue'
